idf_component_register(
    SRCS
        "app_main.cpp" 
        "${my_idf_libs_SOURCE_DIR}/provision/provision.cpp"
        "${my_idf_libs_SOURCE_DIR}/sntp/sntp.cpp"
        "clock_tm.cpp"
        "${my_idf_libs_SOURCE_DIR}/display/blink.cpp" 
        "${my_idf_libs_SOURCE_DIR}/sensors/sensor_event.cpp"
        "${my_idf_libs_SOURCE_DIR}/sensors/lighting.cpp"
        "${my_idf_libs_SOURCE_DIR}/sensors/htu2x.cpp"
        "${my_idf_libs_SOURCE_DIR}/proto/json_wrapper.cpp"
        "${my_idf_libs_SOURCE_DIR}/proto/handler.cpp"
        "${my_idf_libs_SOURCE_DIR}/proto/defines.cpp"
        "${my_idf_libs_SOURCE_DIR}/proto/http_server.cpp"
        "${my_idf_libs_SOURCE_DIR}/utils/utils.cpp" 
        "${my_idf_libs_SOURCE_DIR}/utils/kvs.cpp"
        #-----------------
        "${my_idf_libs_SOURCE_DIR}/test/tst_utils.cpp"
        "${my_idf_libs_SOURCE_DIR}/proto/test/tst_handler.cpp"
       
    INCLUDE_DIRS
        "." 
        "${my_idf_libs_SOURCE_DIR}" 
    REQUIRES
        nvs_flash 
        wifi_provisioning 
        json 
        esp_wifi 
        driver 
        spi_flash
        si7021
        unity
        esp_http_server
    )
